artifact_uri: file:///home/ubuntu/MLflow_churn_prediction/mlruns/670066201955369732/cd96c98fdf4d496f90b4ab9e0ded64b2/artifacts
end_time: 1777975159069
entry_point_name: ''
experiment_id: '670066201955369732'
lifecycle_stage: active
run_id: cd96c98fdf4d496f90b4ab9e0ded64b2
run_name: Model_Evaluation
source_name: ''
source_type: 4
source_version: ''
start_time: 1777975140193
status: 3
tags: []
user_id: ubuntu
