creation_timestamp: 1777943631810
current_stage: Staging
deployment_job_state: null
description: null
last_updated_timestamp: 1777943631876
model_id: null
name: ChurnModel
run_id: 00d55ad0f2504771bdef8f0e122a0d1f
run_link: null
source: file:////mlflow/tmp/mlruns/670066201955369732/00d55ad0f2504771bdef8f0e122a0d1f/artifacts/model
status: READY
status_message: null
storage_location: file:////mlflow/tmp/mlruns/670066201955369732/00d55ad0f2504771bdef8f0e122a0d1f/artifacts/model
user_id: null
version: 12
