artifact_uri: file:///home/ubuntu/MLflow_churn_prediction/mlruns/670066201955369732/3bc67eac570b41318add132a2cb5eee2/artifacts
end_time: 1777933049885
entry_point_name: ''
experiment_id: '670066201955369732'
lifecycle_stage: active
run_id: 3bc67eac570b41318add132a2cb5eee2
run_name: unequaled-worm-913
source_name: ''
source_type: 4
source_version: ''
start_time: 1777933040196
status: 3
tags: []
user_id: ubuntu
