artifact_uri: file:///home/ubuntu/MLflow_churn_prediction/mlruns/670066201955369732/18ececc8a3ee47d59e189ef3ab5c8b9b/artifacts
end_time: 1777976360324
entry_point_name: ''
experiment_id: '670066201955369732'
lifecycle_stage: active
run_id: 18ececc8a3ee47d59e189ef3ab5c8b9b
run_name: Model_Evaluation
source_name: ''
source_type: 4
source_version: ''
start_time: 1777976356683
status: 3
tags: []
user_id: root
